apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
  labels:
    name: demo
spec:
  replicas: 0
  selector:
    matchLabels:
      name: demo
  template:
    metadata:
      labels:
        name: demo
    spec:
      containers:
        - name: demo
          image: xxx/demo:tag
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - '-c'
                  - kill -TRAP 1 && tail --pid=1 -f /dev/null
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: { }
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600